name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    name: Builds the subgraph to ensure it compiles correctly
    runs-on: ubuntu-latest
    env:
      NETWORK_NAME: mainnet
      START_BLOCK_NUMBER: 14265505
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 18.x

      - name: Setup SSH keys and hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SUBGRAPH_DEPLOY_KEY }}"

      - name: Install dependencies
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: yarn install --frozen-lockfile

      - name: Install graph cli
        run: sudo apt-get install libsecret-1-dev; yarn global add @graphprotocol/graph-cli;

      - name: Authorize
        run: graph auth --product hosted-service ${{secrets.GRAPH_ACCESS_TOKEN}}

      - name: Install contracts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: git submodule update --init

      - name: Compile
        run: yarn codegen

      - name: Build
        run: yarn build

  deploy-dev:
    name: Deploy the subgraph to dev
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    env:
      NETWORK_NAME: mainnet
      START_BLOCK_NUMBER: 14265505
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16.x

      - name: Setup SSH keys and hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SUBGRAPH_DEPLOY_KEY }}"

      - name: Install dependencies
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: yarn install --frozen-lockfile

      - name: Install graph cli
        run: sudo apt-get install libsecret-1-dev; yarn global add @graphprotocol/graph-cli;

      - name: Authorize
        run: graph auth --product hosted-service ${{secrets.GRAPH_ACCESS_TOKEN}}

      - name: Install contracts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: git submodule update --init

      - name: Compile
        run: yarn codegen

      - name: Build
        run: yarn build

      - name: Deploy
        run: yarn deploy-dev

  deploy-prod:
    name: Deploy the subgraph to prod
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      NETWORK_NAME: mainnet
      START_BLOCK_NUMBER: 14265505
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16.x

      - name: Setup SSH keys and hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SUBGRAPH_DEPLOY_KEY }}"

      - name: Install dependencies
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: yarn install --frozen-lockfile

      - name: Install graph cli
        run: sudo apt-get install libsecret-1-dev; yarn global add @graphprotocol/graph-cli;

      - name: Authorize
        run: graph auth --product hosted-service ${{secrets.GRAPH_ACCESS_TOKEN}}

      - name: Install contracts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: git submodule update --init

      - name: Compile
        run: yarn codegen

      - name: Build
        run: yarn build

      - name: Deploy ETH Mainnet
        run: yarn deploy-prod

      - name: Deploy Fantom
        run: yarn deploy-ftm
